import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import SectionLayout from "../components/SectionLayout/SectionLayout";
import SectionOneCard from "../components/SectionOneCard/SectionOneCard";
import SecondCardSection from "../components/SecondCard/SecondCardSection";
import ThirdCard from "../components/ThirdCard/ThirdCard";
import FourthCardSection from "../components/FourthCardSection/FourthCardSection";
import FifthSectionCard from "../components/FifthSectionCard/FifthSectionCard";
import AOS from "aos";
import { useEffect } from "react";
import "aos/dist/aos.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	useEffect(() => {
		AOS.init({ duration: 2000 });
	}, []);
	return (
		<>
			<Head>
				<title>Crestal</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/logo.png" />
			</Head>
			<main>
				<div>
					<SectionLayout>
						<div className="relative">
							<SectionOneCard />
							<SecondCardSection />
							<ThirdCard />
							<FifthSectionCard />
							<FourthCardSection />
						</div>
					</SectionLayout>
				</div>
			</main>
		</>
	);
}
